application:
  version: '@project.version@'
logging:
  level:
    com:
      alberto:
        bikecheck: DEBUG
    org:
      springframework: ERROR
  pattern:
    console: '%d{HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n'
log4j:
  logger:
    com:
      alberto:
        bikecheck: DEBUG
server:
  port: 8090
spring:
  datasource:
    driverClassName: org.h2.Driver
    password: password
    username: sa
    url: jdbc:h2:mem:testdb
  h2:
    console:
      path: /h2-console
      enabled: 'true'
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
springdoc:
  swagger-ui:
    operationsSorter: method
    path: /swagger-ui-custom.html
